spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/oauth2/jwks
  datasource:
    url: jdbc:postgresql://localhost:5432/TacoCloud
    username: TacoCloud
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    rest:
      base-path: /data-api
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: ja09091990
taco:
  orders:
    pageSize: 10