spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/oauth2/jwks
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/TacoCloud
    username: TacoCloud
    password: 123
  data:
    r2dbc:
      repositories:
        enabled: true
    rest:
      base-path: /data-api
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: ja09091990
  kafka:
    bootstrap-servers:
      - localhost:9092
    producer:
      keySerializer: org.springframework.kafka.support.serializer.JsonSerializer
      valueSerializer: org.springframework.kafka.support.serializer.JsonSerializer
    template:
      default-topic: orders
taco:
  tacos:
    tacosPageSize: 12
  orders:
    ordersPageSize: 10